---
title: "Entrega Final - Introducción a la Ciencia de Datos"
author: "Grupo 8: Facundo Morini, Cecilia Waksman"
lang: es
format:
  pdf:
    titlepage: true
    include-in-header:
      text: |
        \usepackage{booktabs}
        \usepackage{float}
        \usepackage{titling}
        \setlength{\droptitle}{-2.5cm}
        \posttitle{\par\end{center}\vspace{-0.8em}}
execute:
    echo: false
    warning: false
    message: false
---

```{r}
library(reticulate)

# use_python(
#     "C:/Users/facur/anaconda3/envs/fertcast/python.exe",
#     required = TRUE
# )

Sys.setenv(RETICULATE_PYTHON = here::here(".venv/bin/python"))

```

```{python}
import pandas as pd
```


# Descripción de los dato


**Falta:**
- Fuente y descripción general
- Tabla de variables sin limpiar los datos, agrupar valores ni generar nuevas variables
- Importancia?


# Problemas de calidad

## Datos faltantes

Un problema clásico a abordar es la existencia de valores nulos. En la tabla \ref{tab:datos_nulos} se observa que existen variables con dicho problema.

```{python}
#| results: asis

df = pd.read_csv("dhs_6_7.csv")

# Cantidad de NA por variable
na = df.isna().sum()

# Porcentaje de NA
na_pct = df.isna().mean()*100

tabla_na = pd.DataFrame({
    "NA": na,
    "%": na_pct.round(2)
})
tabla_na = tabla_na[tabla_na["NA"] > 0].sort_values("NA", ascending=False)

nombres = {
    "v212": "Edad al primer hijo",
    "v503": "Cantidad de uniones",
    "v715": "Años de educación de la pareja",
    "v836": "Cantidad de parejas sexuales",
    "v717": "Ocupación de la mujer",
    "v301": "Conocimiento de métodos anticonceptivos",
    "v364": "Intención de uso de métodos anticonceptivos",
    "v531": "Edad al primer acto sexual",
    "v613": "Número ideal de hijos"
}

tabla_na_con_na = tabla_na[tabla_na["NA"] > 0].copy()

# Reemplazar los códigos por los nombres
tabla_na_con_na.index = tabla_na_con_na.index.map(nombres)

tabla_na_con_na=tabla_na_con_na.to_latex(
    index=False,
    escape=True,
    caption="Variables con datos nulo.",
    label="tab:datos_nulos"
)

tabla_na_con_na = tabla_na_con_na.replace(
    "\\begin{table}",
    "\\begin{table}\n\\centering"
)

print(tabla_na_con_na)
```

No todos los datos nulos son un error en la encuesta, por ejemplo: que la edad al primer hijo sea nula, puede significar que la mujer encuestada todavía no ha tenido hijos.

```{python}
resumen = pd.DataFrame({
    "tipo": df.dtypes,
    "min": df.min(numeric_only=False),
    "max": df.max(numeric_only=False),
    "n_unicos": df.nunique()
})

#print(resumen)

# v119 v121 v157 v158 v159 v364 v536 ??
# v212 inconsistencia
# v531 v613 v715 v717 v836 son los 97, 98 y 99
```



Los valores nulos no siempre se presentan como elementos vacíos, si no que en muchas encuestas se declaran con un cierto valor fuera del recorrido esperado de la variable. En esta encuesta se declararon datos faltantes con los valores 97, 98 y 99 para las variables: edad al primer acto sexual, número ideal de hijos, total de años de educación de la pareja, ocupación y cantidad de parejas sexuales que ha tenido.

## No respuesta

A la ausencia de datos viene relacionada la no respuesta, tanto parcial como total. Algunas preguntas, especialmente aquellas vinculadas a la fecundidad, sexualidad o planificación familiar, pueden presentar una mayor proporción de respuestas faltantes debido a rechazo, desconocimiento o incomodidad de las entrevistadas. Este razonamiento coincide con las variables que presentan datos faltantes. Si la probabilidad de no responder está asociada con características de las mujeres o con la propia variable de interés, los análisis realizados únicamente sobre los casos completos pueden producir estimaciones sesgadas y disminuir la representatividad de los resultados.

## Valores inconsistentes

Otro posible problema es la existencia de valores que no coinciden con el recorrido esperado de una variable. Por ejemplo: que la edad al primer hijo sea 3 es irreal, por lo que estos datos también deberían ser considerados nulos, ya que seguramente corresponden a un error en el llenado de la encuesta.


```{python}
#v012>v212>v531
aux = df[["v012", "v212", "v531"]].dropna()

inconsistentes = aux[
    (aux["v012"] < aux["v212"]) |
    (aux["v212"] < aux["v531"])
]

inconsistencias_fuera_rango = inconsistentes[
    ~inconsistentes["v531"].between(96, 99)
]

#print(inconsistencias_fuera_rango)

```

También pueden existir inconsistencias entre variables. Se espera que la edad de la mujer encuestada sea mayor o igual a su edad al primer hijo y, a su vez, que esta sea mayor o igual que su edad al primer acto sexual, pero esto no se cumple para 5 observaciones de mujeres encuestadas.

## Sesgo de respuesta

Existe otro tipo de problemas que no son visibles en los datos, ya que corresponden a diferencias no constatables entre la realidad y la respuesta de la encuestada, o a subjetividades propias de la misma. La presencia de posibles sesgos en la respuesta es uno de estos casos. Varias de las variables relevadas corresponden a comportamientos o preferencias personales, por lo que las respuestas pueden verse afectadas por el contexto social y cultural. Por ejemplo, el número ideal de hijos refleja una preferencia declarada y no necesariamente el deseo real de la entrevistada. En contextos donde existen fuertes normas sociales respecto al tamaño de la familia, las personas pueden responder aquello que consideran socialmente aceptable en lugar de expresar su verdadera preferencia. Asimismo, algunas entrevistadas pueden modificar sus respuestas para que sean coherentes con el número de hijos que ya tienen. Un segundo ejemplo es la edad al primer acto sexual. Socialmente puede estar mal visto tener un primer encuentro sexual a edades muy tempranas o muy tardías, por lo que esto puede generar en la encuestada la necesidad de responder de acuerdo a aquello considerado culturalmente correcto, en lugar de la edad real.



# Preguntas planteada

En base al punto anterior, nos hemos cuestionado cuál sería la mejor estrategia para atacar cada uno de los problemas de calidad mencionados. Una vez resueltos dichos problemas, es de nuestro interés modelar la edad al primer hijo, ya que es un indicador relevante al estudiar las dinámicas familiares y la planificación demográfica entre distintas poblaciones. Para ello, nos parece relevante encontrar qué modelos se pueden apilcar a este problema y cuál es el mejor de ellos.

# Posibles soluciones

**Falta: qué visualizaciones usaría, tanto para explorar los datos como para explicar resultados**

## Limpieza de datos

Como primer paso, se debería comenzar sustituyendo valores que representan datos faltantes, valores inconsistentes con el recorrido de la variable y valores inconsistentes entre variables por valores nulos. De esta forma, se puede abordar el problema de forma más ordenada.

En variables numéricas los datos nulos se pueden sustituir por su media o mediana. En el caso particular de la cantidad de parejas sexuales, como esta variable no cuenta con ninguna respuesta de valor 0, se podría creer que los datos faltantes corresponden a este valor y sustituir por el mismo. Por su lado, en variables categóricas, se podrían sustituir los valores nulos por la categoría modal. Si alguna de las variables cuenta con un porcentaje muy alto de datos nulos, quizás sea mejor optar por no usar la misma para el análisis o modelado pertinente.

## Sesgo de respuesta

El sesgo en los datos acutales no se puede cuantificar, por lo que únicamente se pueden proponer mejoras para futuras encuestas. La redacción de las preguntas en una encuesta debe revisada minuciosamente, para así no cargar las mismas con una connotación indeseada y para que sean lo más claras posible. También es necesario brindar una buena capaitación al equipo encuestador, de forma que al momento de la encuesta no hayan complicaciones y que las encuestadas se sientan cómodas en un ambiente seguro, que las incite a responder con mayor confianza y veracidad.

## No respuesta

Para analizar el efecto de la no respuesta parcial, se podría comparar el perfil de las encuestadas que no respondieron cierta pregunta para hayar similitudes entre ellas y diferencias con el resto de encuestadas que sí respondieron. Esto también es un indicio sobre la no respuesta total, ya que estas posibles caracterísicas halladas, quizás se presentn también por el grupo de mujeres que decidió no responder la encuesta. En base a esta información, se pueden aplicar herramientas específicas para intentar obtener una mayor tasa de respuesta.


## Modelado de la edad al primer hijo

**Falta**
Ej.:Random forest, red


# Consideraciones éticas

## Privacidad de los datos

Los datos cuentan con un ID que pseudo-anonimiza la identidad de cada encuestada. Estos IDs se asocian a otra base de datos privada, donde se pueden recuperar los identificadores directos de las mismas. Sin embargo, esta forma de anonimización puede llegar a ser insuficiente, ya que, con los datos proporcionados en las variables, se podría llegar a identificar alguna persona particular. Por esto, se proponen mejores formas de resguardar la identidad de las encuestadas:

- _k-anonymity_: busca que cada combinación de cuasi-identificadores (por ejemplo: edad, país, estrato y cantidad de uniones) corresponda al menos a k personas, de modo que un individuo no pueda distinguirse del resto del grupo. Generalmente se consigue mediante supresión y generalización. Las variables a elegir para determinar cada grupo no deben ser aleatorias, sino que se deben seleccionar las que permitan conservar la mayor información posible o la información más esencial para el fin concreto de la encuesta.

- _l-diversity_: complementa el k-anonimity exigiendo que, dentro de cada grupo anonimizado, exista suficiente diversidad en los atributos sensibles. Así se evita inferir información privada aunque no pueda identificarse exactamente a la persona.

- _t-closeness_: fortalece aún más la protección al exigir que la distribución de los atributos sensibles dentro de cada grupo sea similar a la del conjunto de datos completo, reduciendo el riesgo de inferencias sobre individuos.

Estos métodos priorizan la privacidad de los datos, pero generan una cierta pérdida de información. Es un trade-off que se debe evaluar según la sensibilidad de los datos y su utilidad una vez anonimizados.

## Sesgo en algoritmos

**Falta**

